
#pragma once

#define VIAL_KEYBOARD_UID {0x49, 0x57, 0xBD, 0x3D, 0xC0, 0xA4, 0xF0, 0x3E}

#define VIAL_COMBO_ENTRIES 2
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 2
#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }
